SupplierPortal/Controllers/PrintReportController.cs
using SupplierPortal.Models;
using SupplierPortal.ReportSupport;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace SupplierPortal.Controllers
{
    public class PrintReportController : Controller
    {
        // GET: PrintReport

        public ActionResult Index()
        {
            return View();
        }

        #region No. of PO (3D Pie Chart)

        [ChildActionOnly]
        public PartialViewResult _NumPO(int year, string buyerGroupName)
        {
            //3D Pie Chart
            DataTable dtNumPO_Chart;

            string chart_NumPO;

            DateTime dt = DateTime.Now;
            if (year == -1)
            {
                year = dt.Year;
            }

            ClsReportChart oRptChart = new ClsReportChart();
            dtNumPO_Chart = oRptChart.getDtNumPO_Chart(Session["suppShortName"].ToString(), buyerGroupName, year);
            chart_NumPO = dtNumPO_Chart.Rows[0]["NumPO_Chart"].ToString();

            DataTable dtNumPO;
            dtNumPO = oRptChart.getDtNumPO(Session["suppShortName"].ToString(), buyerGroupName, year);
            int numPORound = dtNumPO.Rows.Count;

            //ChartsModels_NumPO model = new ChartsModels_NumPO();
            ChartsModels_NumPO model = new ChartsModels_NumPO
            {
                data_NumPO = Enumerable.Range(1, numPORound).Select(x => new NumPO
                {
                    //buyerGroup = Convert.ToString(dtNumPO.Rows[x - 1]["BuyerGroup"]),
                    //buyerName = Convert.ToString(dtNumPO.Rows[x - 1]["BuyerName"]),
                    buyer = Convert.ToString(dtNumPO.Rows[x - 1]["Buyer"]),
                    numPO = String.Format("{0:#,##0}", dtNumPO.Rows[x - 1]["NumPO"]),
                    percentNumPO = Convert.ToDecimal(dtNumPO.Rows[x - 1]["PercentNumPO"])
                })
            };
            model.json_NumPO = chart_NumPO;

            //return PartialView("_NumPO", model);
            return PartialView(@"~/Views/PrintReport/_NumPO.cshtml", model);
        }

        [HttpPost]
        public PartialViewResult _NumPO(DashboardModels dModel)
        {
            //3D Pie Chart
            DataTable dtNumPO_Chart;
            string chart_NumPO;

            ClsReportChart oRptChart = new ClsReportChart();
            dtNumPO_Chart = oRptChart.getDtNumPO_Chart(Session["suppShortName"].ToString(), dModel.selectedBuyerGrp, dModel.selectedYear);

            chart_NumPO = dtNumPO_Chart.Rows[0]["NumPO_Chart"].ToString();

            DataTable dtNumPO;
            dtNumPO = oRptChart.getDtNumPO(Session["suppShortName"].ToString(), dModel.selectedBuyerGrp, dModel.selectedYear);
            int numPORound = dtNumPO.Rows.Count;

            //ChartsModels_NumPO model = new ChartsModels_NumPO();
            ChartsModels_NumPO model = new ChartsModels_NumPO
            {
                data_NumPO = Enumerable.Range(1, numPORound).Select(x => new NumPO
                {
                    //buyerGroup = Convert.ToString(dtNumPO.Rows[x - 1]["BuyerGroup"]),
                    //buyerName = Convert.ToString(dtNumPO.Rows[x - 1]["BuyerName"]),
                    buyer = Convert.ToString(dtNumPO.Rows[x - 1]["Buyer"]),
                    numPO = String.Format("{0:#,##0}", dtNumPO.Rows[x - 1]["NumPO"]),
                    percentNumPO = Convert.ToDecimal(dtNumPO.Rows[x - 1]["PercentNumPO"])
                })
            };
            model.json_NumPO = chart_NumPO;
            //return PartialView("_NumPO", model);
            return PartialView(@"~/Views/PrintReport/_NumPO.cshtml", model);
        }

        #endregion

        #region PO Volume (3D Pie Chart)

        [ChildActionOnly]
        public PartialViewResult _POVolume(int year, string buyerGroupName)
        {
            //3D Pie Chart
            DataTable dtPOVolume_Chart;
            string chart_POVolume;

            DateTime dt = DateTime.Now;
            if (year == -1)
            {
                year = dt.Year;
            }

            ClsReportChart oRptChart = new ClsReportChart();
            dtPOVolume_Chart = oRptChart.getDtPOVolume_Chart(Session["suppShortName"].ToString(), buyerGroupName, year);

            chart_POVolume = dtPOVolume_Chart.Rows[0]["POVolume_Chart"].ToString();

            DataTable dtPOVolume;
            dtPOVolume = oRptChart.getDtPOVolume(Session["suppShortName"].ToString(), buyerGroupName, year);
            int POVolumeRound = dtPOVolume.Rows.Count;

            //ChartsModels_NumPO model = new ChartsModels_NumPO();
            ChartsModels_POVolume model = new ChartsModels_POVolume
            {
                data_POVolume = Enumerable.Range(1, POVolumeRound).Select(x => new POVolume
                {
                    buyer = Convert.ToString(dtPOVolume.Rows[x - 1]["Buyer"]),
                    volume = String.Format("{0:#,##0.00}", dtPOVolume.Rows[x - 1]["POVolume"]),
                    percentVolume = Convert.ToDecimal(dtPOVolume.Rows[x - 1]["PercentVolume"])
                })
            };
            model.json_POVolume = chart_POVolume;

           // return PartialView("_POVolume", model);
            return PartialView(@"~/Views/PrintReport/_POVolume.cshtml", model);
        }

        [HttpPost]
        public PartialViewResult _POVolume(DashboardModels dModel)
        {
            //3D Pie Chart
            DataTable dtPOVolume_Chart;
            string chart_POVolume;

            ClsReportChart oRptChart = new ClsReportChart();
            dtPOVolume_Chart = oRptChart.getDtPOVolume_Chart(Session["suppShortName"].ToString(), dModel.selectedBuyerGrp, dModel.selectedYear);

            chart_POVolume = dtPOVolume_Chart.Rows[0]["POVolume_Chart"].ToString();

            DataTable dtPOVolume;
            dtPOVolume = oRptChart.getDtPOVolume(Session["suppShortName"].ToString(), dModel.selectedBuyerGrp, dModel.selectedYear);
            int POVolumeRound = dtPOVolume.Rows.Count;

            //ChartsModels_NumPO model = new ChartsModels_NumPO();
            ChartsModels_POVolume model = new ChartsModels_POVolume
            {
                data_POVolume = Enumerable.Range(1, POVolumeRound).Select(x => new POVolume
                {
                    buyer = Convert.ToString(dtPOVolume.Rows[x - 1]["Buyer"]),
                    volume = String.Format("{0:#,##0.00}", dtPOVolume.Rows[x - 1]["POVolume"]),
                    percentVolume = Convert.ToDecimal(dtPOVolume.Rows[x - 1]["PercentVolume"])
                })
            };
            model.json_POVolume = chart_POVolume;
            //return PartialView("_POVolume", model);
            return PartialView(@"~/Views/PrintReport/_POVolume.cshtml", model);
        }

        #endregion

        #region PO Volume by Status (3D Pie Chart)

        [ChildActionOnly]
        public PartialViewResult _POStatus(int year, string buyerGroupName)
        {
            //3D Pie Chart
            DataTable dtPOStatus_Chart;
            string chart_POStatus;

            DateTime dt = DateTime.Now;
            if (year == -1)
            {
                year = dt.Year;
            }

            ClsReportChart oRptChart = new ClsReportChart();
            dtPOStatus_Chart = oRptChart.getDtPOStatus_Chart(Session["suppShortName"].ToString(), buyerGroupName, year);

            chart_POStatus = dtPOStatus_Chart.Rows[0]["POVolumeByStatus_Chart"].ToString();

            DataTable dtPOStatus;
            dtPOStatus = oRptChart.getDtPOStatus(Session["suppShortName"].ToString(), buyerGroupName, year);
            int POStatusRound = dtPOStatus.Rows.Count;

            //ChartsModels_NumPO model = new ChartsModels_NumPO();
            ChartsModels_POStatus model = new ChartsModels_POStatus
            {
                data_POStatus = Enumerable.Range(1, POStatusRound).Select(x => new POStatus
                {
                    status = Convert.ToString(dtPOStatus.Rows[x - 1]["StatusName"]),
                    volume = String.Format("{0:#,##0.00}", dtPOStatus.Rows[x - 1]["POVolume"]),
                    numPO = String.Format("{0:#,##0}", dtPOStatus.Rows[x - 1]["NumPO"]),
                    percentNumPO = Convert.ToDecimal(dtPOStatus.Rows[x - 1]["PercentNumPO"])
                })
            };
            model.json_POStatus = chart_POStatus;

            //return PartialView("_POStatus", model);
            return PartialView(@"~/Views/PrintReport/_POStatus.cshtml", model);
        }

        [HttpPost]
        public PartialViewResult _POStatus(DashboardModels dModel)
        {
            //3D Pie Chart
            DataTable dtPOStatus_Chart;
            string chart_POStatus;

            ClsReportChart oRptChart = new ClsReportChart();
            dtPOStatus_Chart = oRptChart.getDtPOStatus_Chart(Session["suppShortName"].ToString(), dModel.selectedBuyerGrp, dModel.selectedYear);

            chart_POStatus = dtPOStatus_Chart.Rows[0]["POVolumeByStatus_Chart"].ToString();

            DataTable dtPOStatus;
            dtPOStatus = oRptChart.getDtPOStatus(Session["suppShortName"].ToString(), dModel.selectedBuyerGrp, dModel.selectedYear);
            int POStatusRound = dtPOStatus.Rows.Count;

            //ChartsModels_NumPO model = new ChartsModels_NumPO();
            ChartsModels_POStatus model = new ChartsModels_POStatus
            {
                data_POStatus = Enumerable.Range(1, POStatusRound).Select(x => new POStatus
                {
                    status = Convert.ToString(dtPOStatus.Rows[x - 1]["StatusName"]),
                    volume = String.Format("{0:#,##0.00}", dtPOStatus.Rows[x - 1]["POVolume"]),
                    numPO = String.Format("{0:#,##0}", dtPOStatus.Rows[x - 1]["NumPO"]),
                    percentNumPO = Convert.ToDecimal(dtPOStatus.Rows[x - 1]["PercentNumPO"])
                })
            };
            model.json_POStatus = chart_POStatus;

SupplierPortal/Views/PrintReport/SummaryReport.cshtml
@model SupplierPortal.Models.DashboardModels
<script src="@Url.Content("~/FusionCharts/FusionCharts.js")" type="text/javascript"></script>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script>
<script>
    $(document).ready(function () {
        $("#filter_detail").html('@T("_MenuSub.SupplyTool.Report.ReportFilterDetail")&nbsp;:&nbsp;@(Model.filterCondition)');
        $("#LastUpdate").html('@(Model.RptLastUpdate)')
        //        $('#user_name').html('@(Model.UserName)');
        //        $('#supplier_name').html('@(Model.SuppShortName)');
        setFooter();
        //$.unblockUI();
    });
</script>
@{
    ViewBag.Title = "Supplier Dashboard";
    Layout = "~/Views/Shared/_LayoutPrintReport.cshtml";
}

<div style="padding:0px 8px 0px 10px;">
    <div class="print_header">
        <div style="float:left;font-size:18px;">BestSupply Dashboard</div>
    </div>
</div>
@*<div class="ms_content">*@
    <div style="padding:2px 8px 5px 8px; width: 825px;">
        <table>
            <tr>
                <td><div id="filter_detail" class="report_topic" style="display:inline-block;"></div></td>
                <td></td>
                <td>
                    <div style="float: right;">
                        <a href="javascript:printpage();">Print</a>
                        <a href="javascript:printpage();"><img src="../Content/images/printer.gif" /></a>
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <table id="tbl_ChartNumPO" border="0" cellpadding="0" cellspacing="0" style="width: 540px; border:solid 1px #AAAAAA;">
                        <tr>
                            <td valign="top" align="center" style="padding:0;">
                                @*3D Pie Chart NumPO*@
                                <div id="ChartNumPO">
                                    @Html.Action("_NumPO", "PrintReport", new { year =2013, buyerGroupName = "All" })
                                </div>
                            </td>
                        </tr>
                    </table>
                </td>
                <td>
                    <div style="padding-left:30px;"></div>
                </td>
                <td>
                    @*<div style="padding-top:22px;"></div>  *@
                    <table id="tbl_ChartPOVolume" border="0" cellpadding="0" cellspacing="0" style="width: 540px; border:solid 1px #AAAAAA;">
                        <tr>
                            <td valign="top" align="center" style="padding:0;">
                                @*3D Pie Chart POVolume*@
                                <div id="ChartPOVolume">
                                    @Html.Action("_POVolume", "PrintReport", new { year = 2013, buyerGroupName = "All" })
                                </div>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
            <tr>
                <td>
                    <div style="padding-left:30px;"></div>
                </td>
                <td>
                    <div style="padding-left:30px;"></div>
                </td>
            </tr>
            <tr>
                <td>
                    <div style="padding-top:22px;"></div>
                    <table id="tbl_ChartPOStatus" border="0" cellpadding="0" cellspacing="0" style="width: 540px; border:solid 1px #AAAAAA;">
                        <tr>
                            <td valign="top" align="center" style="padding:0;">
                                @*3D Pie Chart POStatus*@
                                <div id="ChartPOStatus">
                                    @Html.Action("_POStatus", "PrintReport", new { year = 2013, buyerGroupName = "All" })
                                </div>
                            </td>
                        </tr>
                    </table>
                </td>
                <td>
                    <div style="padding-left:30px;"></div>
                </td>
            </tr>
        </table>
    </div>
</div>
<div style="padding:5px 10px 0px 20px;">
    <div class="print_by" align="right">
        Supplier: <span id="supplier_name"></span>
        &nbsp;พิมพ์โดย (Print By): <span id="user_name"></span>
        &nbsp;พิมพ์เมื่อวันที่ (Print Date):  <span id="print_date"></span>
    </div>
</div>
<div style="padding:5px 10px 10px 10px;">
    <div style="border-top:solid 1px #CCCCCC;"></div>
</div>
<script type="text/javascript">

    //    $.blockUI({
    //        message: $('#loadingMsg'),
    //        overlayCSS: { backgroundColor: '#FFFFFF' },
    //        css: {
    //            border: 'none',
    //            background: 'none',
    //            padding: '0px'
    //        }
    //    });

    //Print
    function printpage() {
        //window.print();
        FusionCharts.printManager.enabled(true);
        FusionCharts.printManager.managedPrint();
    }

    function setFooter() {
        var today = new Date();
        var dd = today.getDate();
        var mm = today.getMonth() + 1; //January is 0!
        var hh = today.getHours();
        var min = today.getMinutes();
        var yyyy = today.getFullYear();
        if (dd < 10) {
            dd = '0' + dd
        }
        if (mm < 10) {
            mm = '0' + mm
        }
        if (hh < 10) {
            hh = '0' + hh
        }
        if (min < 10) {
            min = '0' + min
        }
        today = mm + '/' + dd + '/' + yyyy + '&nbsp;' + hh + ':' + min;
        $('#user_name').html('@(Model.UserName)');
        $('#supplier_name').html('@(Model.SuppShortName)');
        $("#print_date").html(today);
    }

</script>

SupplierPortal/Views/PrintReport/_NumPO.cshtml
@model SupplierPortal.Models.ChartsModels_NumPO
<script src="@Url.Content("~/FusionCharts/FusionCharts.js")" type="text/javascript"></script>


<div id="_NumPO_"></div>

@*<table class='sel_sup_tbl' cellspacing='0' cellpadding='0' align='center' width='100%'>
        <thead>
            <tr>
                <th class='chart_data_th_no_link' width='80'>&nbsp;</th>
                @foreach (var item in Model.data_NumPO)
                {
                    <th class='chart_data_th' width='100'>@Html.DisplayFor(modelItem => item.buyerShortName) </th>
                }
                </tr>
        </thead>
        <tbody>
            <tr>
            <th class='chart_data_th2'>No. of PO</th>
                @foreach (var item in Model.data_NumPO)
                {
                    <td class='chart_data_td' align='right'>
                        <a style='text-decoration:none; color:#7d96ac;'>@Html.DisplayFor(modelItem => item.numPO)</a>
                    </td>
                }
            </tr>
        </tbody>
    </table>*@

<table cellspacing='0' cellpadding='0' align='center' width='100%'>
    <thead>
        <tr>
            <th class='chart_data_th' width='35%'> @T("_Report.Charts.Buyer")</th>
            <th class='chart_data_th' width='30%'> @T("_Report.Charts.NoOf_PO") (%)</th>
            <th class='chart_data_th' width='35%'> @T("_Report.Charts.NoOf_PO")</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td colspan='3'>
                @*<div style="max-height:130px; min-height:20px; overflow-y:scroll; overflow-x:hidden">*@
                <div style="min-height:20px; overflow-y:hidden; overflow-x:hidden">
                    <table cellspacing='0' cellpadding='0' align='center' width='100%' style="border-collapse:collapse; border-color:#bbbbbb">
                        @foreach (var item in Model.data_NumPO)
                        {
                            <tr>
                                <th class='chart_data_th' align='left' width='35%' style="font-size:13px">  @Html.DisplayFor(modelItem => item.buyer) </th>
                                <td class='chart_data_td' align='right' width='30%' style="font-size:13px">
                                    <a style='text-decoration:none; color:#7d96ac;'>@Html.DisplayFor(modelItem => item.percentNumPO)</a>
                                </td>
                                <td class='chart_data_td' align='right' width='35%' style="font-size:13px">
                                    <a style='text-decoration:none; color:#7d96ac;'>@Html.DisplayFor(modelItem => item.numPO)</a>
                                </td>
                            </tr>
                        }
                    </table>
                </div>
            </td>
        </tr>
    </tbody>
</table>

<script type="text/javascript">

    function DecodeHtml(str) {
        return jQuery('<div/>').html(str).text();
    }

    FusionCharts.setCurrentRenderer('javascript');

    var myChart = new FusionCharts("../FusionCharts/Pie3D.swf",
    "chart_NumPO", "510", "340", "0", "1");

    if ('@(Model.json_NumPO)' != "") {
        var chrt_NumPO = DecodeHtml('@(Model.json_NumPO)');
        myChart.setJSONData(JSON.parse(chrt_NumPO));
        //myChart.setJSONData('@(Model.json_NumPO)');
    }

    myChart.configure("ChartNoDataText", "No data!");
    myChart.render("_NumPO_");

</script>

SupplierPortal/Views/PrintReport/_POStatus.cshtml
@model SupplierPortal.Models.ChartsModels_POStatus
<script src="@Url.Content("~/FusionCharts/FusionCharts.js")" type="text/javascript"></script>

<div id="_POStatus_" style="padding-top:1px;"></div>
@*<table class='sel_sup_tbl' cellspacing='0' cellpadding='0' align='center' width='100%'>
        <thead>
            <tr>
                <th class='chart_data_th_no_link' width='80'>&nbsp;</th>
                @foreach (var item in Model.data_POStatus)
                {
                    <th class='chart_data_th' width='100'>@Html.DisplayFor(modelItem => item.status) </th>
                }
            </tr>
        </thead>
        <tbody>
            <tr>
                <th class='chart_data_th2'>No. of PO (%)</th>
                @foreach (var item in Model.data_POStatus)
                {
                    <td class='chart_data_td colChartBuyer" + i + "' align='right'>
                        <a style= 'text-decoration:none; color:#7d96ac;'>@Html.DisplayFor(modelItem => item.percentNumPO)</a>
                    </td>
                }
            </tr>
            <tr>
                <th class='chart_data_th2'>No. of PO</th>
                @foreach (var item in Model.data_POStatus)
                {
                    <td class='chart_data_td colChartBuyer" + i + "' align='right'>
                        <a style= 'text-decoration:none; color:#7d96ac;'>@Html.DisplayFor(modelItem => item.numPO)</a>
                    </td>
                }
            </tr>
            <tr>
                <th class='chart_data_th2'>PO Volume</th>
                @foreach (var item in Model.data_POStatus)
                {
                    <td class='chart_data_td colChartBuyer" + i + "' align='right'>
                        <a style= 'text-decoration:none; color:#7d96ac;'>@Html.DisplayFor(modelItem => item.volume)</a>
                    </td>
                }
            </tr>
        </tbody>
    </table>*@

<table cellspacing='0' cellpadding='0' align='center' width='100%'>
    <thead>
        <tr>
            <th class='chart_data_th' width='30%'> @T("_Report.Charts.Status") </th>
            <th class='chart_data_th' width='20%'>@T("_Report.Charts.NoOf_PO") (%)</th>
            <th class='chart_data_th' width='20%'> @T("_Report.Charts.NoOf_PO") </th>
            <th class='chart_data_th' width='30%'> @T("_Report.Charts.POVolume") </th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td colspan='4'>
                @*<div style="max-height:132px; min-height:20px; overflow-y:scroll; overflow-x:hidden;">*@
                <div style="min-height:20px; overflow-y:hidden; overflow-x:hidden">
                    <table cellspacing='0' cellpadding='0' align='center' width='100%' style="border-collapse:collapse; border-color:#bbbbbb">
                        @foreach (var item in Model.data_POStatus)
                        {
                            <tr>
                                <th class='chart_data_th' align='left' width='30%'>  @Html.DisplayFor(modelItem => item.status) </th>
                                <td class='chart_data_td' align='right' width='20%'>
                                    <a style='text-decoration:none; color:#7d96ac;'>@Html.DisplayFor(modelItem => item.percentNumPO)</a>
                                </td>
                                <td class='chart_data_td' align='right' width='20%'>
                                    <a style='text-decoration:none; color:#7d96ac;'>@Html.DisplayFor(modelItem => item.numPO)</a>
                                </td>
                                <td class='chart_data_td' align='right' width='30%'>
                                    <a style='text-decoration:none; color:#7d96ac;'>@Html.DisplayFor(modelItem => item.volume)</a>
                                </td>
                            </tr>
                        }
                    </table>
                </div>
            </td>
        </tr>
    </tbody>
</table>

<script type="text/javascript">

    function DecodeHtml(str) {
        return jQuery('<div/>').html(str).text();
    }

    FusionCharts.setCurrentRenderer('javascript');

    var myChart = new FusionCharts("../FusionCharts/Pie3D.swf",
    "chart_POStatus", "510", "340", "0", "1");

    if ('@(Model.json_POStatus)' != "") {
        var chrt_POStatus = DecodeHtml('@(Model.json_POStatus)');
        myChart.setJSONData(JSON.parse(chrt_POStatus));
    }

    myChart.configure("ChartNoDataText", "No data!");
    myChart.render("_POStatus_");

</script>

SupplierPortal/Views/PrintReport/_POVolume.cshtml
@model SupplierPortal.Models.ChartsModels_POVolume
<script src="@Url.Content("~/FusionCharts/FusionCharts.js")" type="text/javascript"></script>


<div id="_POVolume_"></div>

@*<table class='sel_sup_tbl' cellspacing='0' cellpadding='0' align='center' width='100%'>
        <thead>
            <tr>
                <th class='chart_data_th_no_link' width='80'>&nbsp;</th>
                @foreach (var item in Model.data_POVolume) {
                    <th class='chart_data_th' width='100'>  @Html.DisplayFor(modelItem => item.buyerShortName) </th>
                }
            </tr>
        </thead>
        <tbody>
            <tr>
                <th class='chart_data_th2'>OP Volume</th>
                @foreach (var item in Model.data_POVolume) {
                    <td class='chart_data_td colChartBuyer" + i + "' align='right'>
                        <a style= 'text-decoration:none; color:#7d96ac;'>@Html.DisplayFor(modelItem => item.volume)</a>
                    </td>
                }
            </tr>
        </tbody>
    </table>*@

<table cellspacing='0' cellpadding='0' align='center' width='100%'>
    <thead>
        <tr>
            <th class='chart_data_th' width='35%'> @T("_Report.Charts.Buyer") </th>
            <th class='chart_data_th' width='30%'> @T("_Report.Charts.POVolume") (%)</th>
            <th class='chart_data_th' width='35%'> @T("_Report.Charts.POVolume") </th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td colspan='3'>
                <div style="min-height:20px; overflow-y:hidden; overflow-x:hidden">
                    <table cellspacing='0' cellpadding='0' align='center' width='100%' style="border-collapse:collapse; border-color:#bbbbbb">
                        @foreach (var item in Model.data_POVolume)
                        {
                            <tr>
                                <th class='chart_data_th' align='left' width='35%' style="font-size:13px">  @Html.DisplayFor(modelItem => item.buyer) </th>
                                <td class='chart_data_td' align='right' width='30%' style="font-size:13px">
                                    <a style='text-decoration:none; color:#7d96ac;'>@Html.DisplayFor(modelItem => item.percentVolume)</a>
                                </td>
                                <td class='chart_data_td' align='right' width='35%' style="font-size:13px">
                                    <a style='text-decoration:none; color:#7d96ac;'>@Html.DisplayFor(modelItem => item.volume)</a>
                                </td>
                            </tr>
                        }
                    </table>
                </div>
            </td>
        </tr>
    </tbody>
</table>



<script type="text/javascript">

    function DecodeHtml(str) {
        return jQuery('<div/>').html(str).text();
    }

    FusionCharts.setCurrentRenderer('javascript');

    var myChart = new FusionCharts("../FusionCharts/Pie3D.swf",
    "chart_Volume", "510", "340", "0", "1");

    if ('@(Model.json_POVolume)' != "") {
        var chrt_POVolume = DecodeHtml('@(Model.json_POVolume)');
        myChart.setJSONData(JSON.parse(chrt_POVolume));
    }

    myChart.configure("ChartNoDataText", "No data!");
    myChart.render("_POVolume_");

    //Add Commas
    function addCommas(nStr) {
        nStr += '';
        x = nStr.split('.');
        x1 = x[0];
        x2 = x.length > 1 ? '.' + x[1] : '';
        var rgx = /(\d+)(\d{3})/;
        while (rgx.test(x1)) {
            x1 = x1.replace(rgx, '$1' + ',' + '$2');
        }
        return x1 + x2;
    }

</script>