SupplierPortal/Controllers/CompanyAdditionalController.cs
using SupplierPortal.Data.Models.SupportModel.CompanyProfile;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SupplierPortal.Data.Models.Repository.CertifiedStd;
using SupplierPortal.Data.Models.Repository.Organization;
using SupplierPortal.Data.Models.MappingTable;
using SupplierPortal.Data.Models.Repository.AppConfig;
using SupplierPortal.Data.Models.Repository.User;
using SupplierPortal.Data.Models.Repository.OrgCertifiedStd;
using SupplierPortal.Data.Models.Repository.OrgCertifiedStdAttachment;
using System.IO;
using SupplierPortal.Services.MainService;
using SupplierPortal.Framework.MethodHelper;
using System.Web.Routing;
using SupplierPortal.Data.Helper;
using SupplierPortal.Services.CompanyProfileManage;
using System.Web.Configuration;
using SupplierPortal.Framework.Localization;

namespace SupplierPortal.Controllers
{
    public class CompanyAdditionalController : ControllerBase
    {
        ICertifiedStdRepository _certifiedStdRepository;
        IOrganizationRepository _organizationRepository;
        IAppConfigRepository _appConfigRepository;
        IUserRepository _userRepository;
        IOrgCertifiedStdRepository _orgCertifiedStdRepository;
        IOrgCertifiedStdAttachmentRepository _orgCertifiedStdAttachmentRepository;
        IComProfileDataService _comProfileDataService;

        public CompanyAdditionalController()
        {
            _certifiedStdRepository = new CertifiedStdRepository();
            _organizationRepository = new OrganizationRepository();
            _appConfigRepository = new AppConfigRepository();
            _userRepository = new UserRepository();
            _orgCertifiedStdRepository = new OrgCertifiedStdRepository();
            _orgCertifiedStdAttachmentRepository = new OrgCertifiedStdAttachmentRepository();
            _comProfileDataService = new ComProfileDataService();
        }

        public CompanyAdditionalController
            (
            CertifiedStdRepository certifiedStdRepository,
            OrganizationRepository organizationRepository,
            AppConfigRepository appConfigRepository,
            UserRepository userRepository,
            OrgCertifiedStdRepository orgCertifiedStdRepository,
            OrgCertifiedStdAttachmentRepository orgCertifiedStdAttachmentRepository,
            ComProfileDataService comProfileDataService
            )
        {
            _certifiedStdRepository = certifiedStdRepository;
            _organizationRepository = organizationRepository;
            _appConfigRepository = appConfigRepository;
            _userRepository = userRepository;
            _orgCertifiedStdRepository = orgCertifiedStdRepository;
            _orgCertifiedStdAttachmentRepository = orgCertifiedStdAttachmentRepository;
            _comProfileDataService = comProfileDataService;
        }

        public ActionResult Certification()
        {
            string username = "";
            if (Session["username"] != null)
            {
                username = Session["username"].ToString();
            }

            int supplierID = _organizationRepository.GetSupplierIDByUsername(username);

            var model = new CompanyCertificationModel();
            model.Proc = "Add";
            model.SupplierID = supplierID;

            var listOrgCertifiedStdAttachment = new List<Tbl_OrgCertifiedStdAttachment>();

            model.OrgCertifiedStdAttachment = listOrgCertifiedStdAttachment;

            return View(model);
        }

        public ActionResult OrgCertifiedStdTable(int supplierID)
        {
            var model = _comProfileDataService.GetOrgCertifiedStdTableBySupplierID(supplierID);

            return PartialView(@"~/Views/CompanyAdditional/_OrgCertifiedStdTablePartial.cshtml", model);
        }

        public PartialViewResult EditCertification(int certId)
        {
            var model = _comProfileDataService.GetCompanyCertificationByCertId(certId);

            model.Proc = "Edit";

            return PartialView(@"~/Views/CompanyAdditional/_CertificateFormPartial.cshtml", model);
        }

        public PartialViewResult ResetCertification()
        {
            string username = "";
            if (Session["username"] != null)
            {
                username = Session["username"].ToString();
            }

            int supplierID = _organizationRepository.GetSupplierIDByUsername(username);

            var model = new CompanyCertificationModel();
            model.Proc = "Add";
            model.SupplierID = supplierID;

            var listOrgCertifiedStdAttachment = new List<Tbl_OrgCertifiedStdAttachment>();

            model.OrgCertifiedStdAttachment = listOrgCertifiedStdAttachment;

            return PartialView(@"~/Views/CompanyAdditional/_CertificateFormPartial.cshtml", model);
        }

        [HttpPost]
        public ActionResult CertificationSave(CompanyCertificationModel model)
        {
            try
            {
                string username = "";
                if (Session["username"] != null)
                {
                    username = Session["username"].ToString();
                }
                var user = _userRepository.FindByUsername(username);
                int userID = user.UserID;

                if (model.Proc == "Add")
                {

                    #region-----------------------Manage OrgCertifiedStd------------------------

                    var orgCertifiedStd = _orgCertifiedStdRepository.GetOrgCertifiedStdBySupplierID(model.SupplierID);

                    int orgCertifiedStdCount = orgCertifiedStd.Count();

                    int seqNo = orgCertifiedStdCount + 1;

                    DateTime validFrom = DateTime.ParseExact(model.ValidFrom, "dd/MM/yyyy",
                                       System.Globalization.CultureInfo.InvariantCulture);

                    DateTime validTo = DateTime.ParseExact(model.ValidTo, "dd/MM/yyyy",
                                       System.Globalization.CultureInfo.InvariantCulture);

                    var orgCertifiedStdModel = new Tbl_OrgCertifiedStd()
                    {
                        SupplierID = model.SupplierID,
                        SeqNo = seqNo,
                        CertifiedID = model.CertifiedID??0,
                        OtherStandardName = model.OtherStandardName??"",
                        ValidFrom = validFrom,
                        ValidTo = validTo
                    };

                    int certId = _orgCertifiedStdRepository.InsertOrgCertifiedStdReturnCertId(orgCertifiedStdModel, userID);

                    #endregion

                    #region-----------------------Manage OrgCertifiedStdAttachment------------------------

                    var hidFile = Request.Params["hidAttachmentName[]"] ?? string.Empty;

                    var hidGuid = Request.Params["hidAttachmentNameUnique[]"] ?? string.Empty;

                    var splitHidFile = hidFile.Split(',');

                    var splitHidGuid = hidGuid.Split(',');

                    if (splitHidFile.Length > 0 && (!string.IsNullOrEmpty(hidFile)))
                    {
                        for (var i = 0; i < splitHidFile.Length; i++)
                        {

                            string fileName = splitHidFile[i];

                            string guidName = splitHidGuid[i];

                            string decodeFileName = StringHelper.GetMakeASCIIStringToComma(fileName.Trim());

                            UploadAttachment(decodeFileName, guidName, certId, userID);

                        }
                        
                    }

                    #endregion
                }else
                {
                    #region-----------------------Manage OrgCertifiedStd------------------------

                    var orgCertifiedStd = _orgCertifiedStdRepository.GetOrgCertifiedStdByCertId(model.CertId??0);

                    if (orgCertifiedStd != null)
                    {
                        DateTime validFrom = DateTime.ParseExact(model.ValidFrom, "dd/MM/yyyy",
                                       System.Globalization.CultureInfo.InvariantCulture);

                        DateTime validTo = DateTime.ParseExact(model.ValidTo, "dd/MM/yyyy",
                                           System.Globalization.CultureInfo.InvariantCulture);

                        orgCertifiedStd.CertifiedID = model.CertifiedID??0;
                        if(model.CertifiedID != -1)
                        {
                            model.OtherStandardName = "";
                        }
                        orgCertifiedStd.OtherStandardName = model.OtherStandardName ?? "";
                        orgCertifiedStd.ValidFrom = validFrom;
                        orgCertifiedStd.ValidTo = validTo;

                        _orgCertifiedStdRepository.Update(orgCertifiedStd, userID);

                    }
                    #endregion

                    #region-----------------------Manage OrgCertifiedStdAttachment------------------------

                    var hidFile = Request.Params["hidAttachmentName[]"] ?? string.Empty;

                    var hidGuid = Request.Params["hidAttachmentNameUnique[]"] ?? string.Empty;

                    var splitHidFile = hidFile.Split(',');

                    var splitHidGuid = hidGuid.Split(',');

                    if (splitHidFile.Length > 0 && (!string.IsNullOrEmpty(hidFile)))
                    {
                        for (var i = 0; i < splitHidFile.Length; i++)
                        {

                            string fileName = splitHidFile[i];

                            string guidName = splitHidGuid[i];

                            string decodeFileName = StringHelper.GetMakeASCIIStringToComma(fileName.Trim());

                            UploadAttachment(decodeFileName, guidName, model.CertId??0, userID);

                        }

SupplierPortal/Views/CompanyAdditional/_CertificateFormPartial.cshtml
@model SupplierPortal.Data.Models.SupportModel.CompanyProfile.CompanyCertificationModel
@{

}
@using (Html.BeginForm("CertificationSave", "CompanyAdditional", FormMethod.Post, new { @id = "mainOrgCertificationForm", }))
{
    string attachmentConfig = SupplierPortal.Framework.MethodHelper.GetConfigDataHelper.GetAppConfigByName("Portal_AttachmentFile");

    int i = 0;

    string attachmentSize = SupplierPortal.Framework.MethodHelper.GetConfigDataHelper.GetAppConfigByName("Portal_AttachmentSize");
    int maxFileSize = Convert.ToInt32(attachmentSize);

    @Html.Hidden("maxFileSize", @maxFileSize, new { @id = "maxFileSize" })
    @Html.HiddenFor(m => m.SupplierID, new { @id = "SupplierID" })
    @Html.HiddenFor(m => m.CertId, new { @id = "CertId" })
    @Html.HiddenFor(m => m.Proc, new { @id = "Proc" })
    <div id="remove_item"></div>
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-body">

                    <div class="row">
                        <div class="col-xs-3 col-md-3">
                            @Html.LabelFor(m => m.CertifiedID, new { @class = "form_label_bold" })<span class="red_highlight">*</span>
                        </div>
                        <div class="col-xs-9 col-md-9">
                            <div class="form-inline">
                                <div class="margin-none">
                                    @Html.Action("CertificateStandard", new { model = Model })
                                </div>
                                <div class="margin-none">
                                    <span class="text-danger-bold" style="display:none;" id="errorCertificate">@T("_ComPro.Certification.ValidateMsg.RequireCertificate")</span>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row" id="divOtherCertificate" style="display:none;">
                        <div class="col-xs-3 col-md-3 form-label-banktext">
                            @Html.Label(" ", new { @class = "form_label_bold" })
                        </div>
                        <div class="col-xs-9 col-md-9">
                            <div class="">
                                <div class="margin-none">
                                    @Html.TextBoxFor(m => m.OtherStandardName, new { @id = "OtherStandardName", @class = "form-control", placeholder = T("_ComPro.Certification.GtxtOtherStandardName"), @style = "width: 280px;" })
                                </div>
                                <div class="margin-none">
                                    <span class="text-danger-bold" style="display:none;" id="errorOtherStandardName">@T("_ComPro.Certification.ValidateMsg.RequireOtherStandardName")</span>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-xs-3 col-md-3">
                            @Html.LabelFor(m => m.ValidFrom, new { @class = "form_label_bold" })<span class="red_highlight">*</span>
                        </div>
                        <div class="col-xs-9 col-md-9">
                            <div class="">
                                <div class="margin-none">
                                    <div class="input-group date" id="datepickerValidFrom">
                                        @Html.TextBoxFor(x => x.ValidFrom, new { @id = "ValidFrom", @class = "form-control", @style = "width: 250px;" })
                                        <span class="input-group-addon">
                                            <span class="glyphicon glyphicon-calendar"></span>
                                        </span>
                                    </div>
                                </div>
                                <div class="margin-none">
                                    @Html.ValidationMessageFor(m => m.ValidFrom, "", new { @class = "text-danger-bold" })
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-xs-3 col-md-3">
                            @Html.LabelFor(m => m.ValidTo, new { @class = "form_label_bold" })<span class="red_highlight">*</span>
                        </div>
                        <div class="col-xs-9 col-md-9">
                            <div class="">
                                <div class="margin-none">
                                    <div class="input-group date" id="datepickerValidTo">
                                        @Html.TextBoxFor(x => x.ValidTo, new { @id = "ValidTo", @class = "form-control", @style = "width: 250px;" })
                                        <span class="input-group-addon">
                                            <span class="glyphicon glyphicon-calendar"></span>
                                        </span>
                                    </div>
                                </div>
                                <div class="margin-none">
                                    @Html.ValidationMessageFor(m => m.ValidTo, "", new { @class = "text-danger-bold" })
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="data_end" style="padding-top:20px;"></div>

                    <div class="row">
                        <div class="col-sm-12 col-md-12">
                            <span class="form_label_bold">@T("_ComPro.Certification.Attachment.InstrTxt.AttachGuide.Title")</span>
                            <span>@T("_ComPro.Certification.Attachment.InstrTxt.AttachGuide.Txt")</span>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-sm-12 col-md-12">
                            <div class="panel panel-default">
                                <div class="panel-body">

                                    <div class="row">
                                        <div class="col-sm-12 col-md-12">
                                            <div class="-custom">
                                                <div class="form-inline-element margin-none">
                                                    <input class="form-control" type="text" id="tbx-file-path" name="tbx-file-path" readonly="readonly" style="width: 230px;" />
                                                </div>
                                                <div class="form-inline-element margin-none">
                                                    <span class="btn btn-default fileinput-button">
                                                        <span>@T("_ComPro.Attachment.BtnBrowse").ToString()</span>
                                                        @Html.TextBox("FileAttachment", null, new { id = "fu-my-simple-upload", type = "file", @accept = "" + @attachmentConfig + "", @class = "fu-my-simple-upload" })
                                                    </span>
                                                </div>
                                                <div class="form-inline-element margin-none">
                                                    <button type="button" class="btn btn-primary hl-start-upload" id="hl-start-upload"><span class="glyphicon glyphicon-upload" style="height:14px;" aria-hidden="true"> </span> <span>@T("_ComPro.Attachment.BtnUpload")</span> </button>
                                                </div>
                                                <div class="form-inline-element margin-none">
                                                    <span id="requiredfileupload" class="text-danger-bold"></span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="data_end" style="padding-top:10px;"></div>

                                    @*<div id="remove_item"></div>*@

                                    <div class="row">
                                        <div class="col-sm-12 col-md-12">
                                            <table width="100%" border="0" cellpadding="0" cellspacing="0" align="center" class="main_table" id="listCertificateDoc">
                                                <thead>
                                                    <tr class="regis_table_header">
                                                        <td width="50%">@T("_ComPro.Certification.Attachment.TblOrgCertifiedStdAttachment.ColCaption.FileName")</td>
                                                        <td width="40%">@T("_ComPro.Certification.Attachment.TblOrgCertifiedStdAttachment.ColCaption.FileSize")</td>
                                                        <td width="10%">@T("_ComPro.Certification.Attachment.TblOrgCertifiedStdAttachment.ColCaption.Action")</td>
                                                    </tr>
                                                </thead>
                                                <tbody id="p_scents">
                                                    @foreach (var item in Model.OrgCertifiedStdAttachment)
                                                    {
                                                        string linkDelete = "<input type=\"image\" src=\"/Content/images/icon/ico-sp_deluser2.gif\" alt=\"Delete\" onclick=\"return deleteAttachment('" + item.AttachmentID + "');\" data-toggle=\"tooltip\" data-placement=\"left\" title=\"Delete file\">";

                                                        i++;

                                                        string pathSave = SupplierPortal.Framework.MethodHelper.GetConfigDataHelper.GetAppConfigByName("Portal_SupplierCertificateDocPath");
                                                        string pathForSaving = pathSave + item.CertId;

                                                        string virtualFilePath = pathForSaving + "/" + item.AttachmentNameUnique;

                                                        string fileSize = SupplierPortal.Services.RegisterPortalManage.RegisterService.GetFileSize(Convert.ToInt32(item.SizeAttach));

                                                        <tr class="main_table_row" id="item_@item.AttachmentID">
                                                            <td align="left">
                                                                <div class="file-attachment-download">
                                                                    @Html.ActionLink(item.AttachmentName, "Download", new { filePath = virtualFilePath }, new { @class = "register" })
                                                                </div>
                                                                @*<input type="hidden" name="hidAttachmentName[]" value="@item.AttachmentName" />
                                                                    <input type="hidden" name="hidAttachmentNameUnique[]" value="@item.AttachmentNameUnique" />*@
                                                            </td>
                                                            <td align="right">@fileSize</td>
                                                            <td align="center">@Html.Raw(linkDelete)</td>
                                                        </tr>
                                                    }
                                                    @if (i == 0)
                                                    {
                                                        <tr class="main_table_row" id="lastData">
                                                            <td style="text-align: center" colspan="3">@T("_ComPro.Certification.Attachment.TblOrgCertifiedStdAttachment.LblNoData")</td>
                                                        </tr>
                                                    }
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>

                                    <div class="data_end" style="padding-top:10px;"></div>

                                    <div style="display:none;">
                                        <input type="submit" value="" id="btnSubmit" />
                                    </div>

                                    @*<div class="row">
                                            <div lass="col-xs-12 col-md-12">
                                                <div class="text-center">
                                                    @Ajax.ActionLink(T("_Global.BtnReset").ToString(), "ResetCertification", null, new AjaxOptions() { UpdateTargetId = "mainOrgCertificationForm", InsertionMode = InsertionMode.ReplaceWith, OnSuccess = "formResetSuccess" }, new { id = "btnReset", @class = "btn btn-default" })
                                                </div>
                                            </div>
                                        </div>*@

                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
}

SupplierPortal/Views/CompanyAdditional/_CertificateStandardPartial.cshtml
@model SupplierPortal.Data.Models.SupportModel.CompanyProfile.CompanyCertificationModel

@Html.DropDownListFor(m => m.CertifiedID, new SelectList(ViewBag.CertificateList, "CertifiedID", "StandardName"), T("_ComPro.Certification.DdlCertificate.OptionLable").ToString(), new { @class = "form-control custom", id = "CertifiedID", @style = "width: 280px;", @onchange = "CertifiedChangedNew(this.value);" })

SupplierPortal/Views/CompanyAdditional/_OrgCertifiedStdTablePartial.cshtml
@model IEnumerable<SupplierPortal.Data.Models.SupportModel.CompanyProfile.OrgCertifiedStdTableModel>
@{
    int i = 0;
}
<div class="col-sm-12 col-md-12">
    <table width="100%" border="0" cellpadding="0" cellspacing="0" align="center" class="main_table" id="list-certifiedStd">
        <thead>
            <tr class="regis_table_header">
                <td width="5%">@T("_ComPro.Certification.TblOrgCertifiedStd.ColCaption.No")</td>
                <td width="35%">@T("_ComPro.Certification.TblOrgCertifiedStd.ColCaption.Certification")</td>
                <td width="25%">@T("_ComPro.Certification.TblOrgCertifiedStd.ColCaption.ValidityFrom")</td>
                <td width="25%">@T("_ComPro.Certification.TblOrgCertifiedStd.ColCaption.ValidityTo")</td>
                <td width="10%">@T("_ComPro.Certification.TblOrgCertifiedStd.ColCaption.Action")</td>
            </tr>
        </thead>
        <tbody>
            @foreach (var itemList in Model)
            {
                int rowCount = itemList.OrgCertifiedStdAttachment.Count();
                int rowspan = rowCount + 1;
                string linkDelete = "<a  data-toggle=\"tooltip\" data-placement=\"left\" title=\"Delete Certification\" onclick=\"deleteCertification('" + itemList.CertId + "');\" style=\"cursor:pointer;\" ><img src=\"/Content/images/icon/ico-sp_deluser2.gif\"></a>";

                string otherStandardName = "";
                if (itemList.CertifiedID == -1)
                {
                    otherStandardName = "(" + itemList.OtherStandardName + ")"; ;
                }
                else
                {
                    otherStandardName = "";
                }

                <tr class="main_table_row numbered_row">
                    <td align="center" class="row_number" rowspan="@rowspan">@itemList.SeqNo</td>
                    <td align="left">@itemList.StandardName @otherStandardName</td>
                    <td align="left">@itemList.ValidFrom</td>
                    <td align="left">@itemList.ValidTo</td>
                    <td align="center" rowspan="@rowspan">
                        @Html.Raw(Ajax.ActionLink("_edit_", "EditCertification", new { certId = itemList.CertId },
                 new AjaxOptions()
                 {
                     UpdateTargetId = "mainOrgCertificationForm",
                     InsertionMode = InsertionMode.ReplaceWith,
                     OnSuccess = "formEditSuccess"

                 }, new { id = "editCertification", title = "Edit Certification" })
                                  .ToHtmlString()
                               .Replace("_edit_", "<img src='/Content/images/icon/ico-sp_edituser2.gif' />").ToString())
                        @Html.Raw(linkDelete)
                    </td>
                </tr>
                foreach (var item in itemList.OrgCertifiedStdAttachment)
                {
                    string pathSave = SupplierPortal.Framework.MethodHelper.GetConfigDataHelper.GetAppConfigByName("Portal_SupplierCertificateDocPath");
                    string pathForSaving = pathSave + item.CertId;

                    string virtualFilePath = pathForSaving + "/" + item.AttachmentNameUnique;

                    <tr class="main_table_row">
                        <td align="left" colspan="3">
                            <div class="file-attachment-download">
                                @Html.ActionLink(item.AttachmentName, "Download", new { filePath = virtualFilePath, fileName = item.AttachmentName }, new { @class = "register" })
                            </div>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

@*<div>
        <table width="100%" border="0" cellpadding="0" cellspacing="0" align="center" class="main_table" id="list-certifiedStd2">
            <thead>
                <tr class="regis_table_header">
                    <td width="5%">@T("_ComPro.Certification.TblOrgCertifiedStd.ColCaption.No")</td>
                    <td width="35%">@T("_ComPro.Certification.TblOrgCertifiedStd.ColCaption.Certification")</td>
                    <td width="25%">@T("_ComPro.Certification.TblOrgCertifiedStd.ColCaption.ValidityFrom")</td>
                    <td width="25%">@T("_ComPro.Certification.TblOrgCertifiedStd.ColCaption.ValidityTo")</td>
                    <td width="10%">@T("_ComPro.Certification.TblOrgCertifiedStd.ColCaption.Action")</td>
                </tr>
            </thead>
            <tbody>
                <tr class="main_table_row numbered_row">
                    <td align="center" class="row_number" rowspan="2">1</td>
                    <td align="left">GMP </td>
                    <td align="left">20/08/2015</td>
                    <td align="left">30/08/2015</td>
                    <td align="center" rowspan="2">
                        <a data-ajax="true" data-ajax-mode="replace-with" data-ajax-update="#mainOrgCertificationForm" href="/CompanyAdditional/EditCertification?certId=7" id="editCertification" title="Edit Certification"><img src="/Content/images/icon/ico-sp_edituser2.gif"></a>
                        <a data-toggle="tooltip" data-placement="left" title="Delete Certification" onclick="deleteCertification('7');" style="cursor:pointer;"><img src="/Content/images/icon/ico-sp_deluser2.gif"></a>
                    </td>
                </tr>
                <tr class="main_table_row">
                    <td align="left" colspan="3">4444 </td>
                </tr>

                <tr class="main_table_row numbered_row" rowspan="2">
                    <td align="center" class="row_number" rowspan="2">2</td>
                    <td align="left">ISO/IEC 17025 </td>
                    <td align="left">20/08/2015</td>
                    <td align="left">28/08/2015</td>
                    <td align="center" rowspan="2">
                        <a data-ajax="true" data-ajax-mode="replace-with" data-ajax-update="#mainOrgCertificationForm" href="/CompanyAdditional/EditCertification?certId=8" id="editCertification" title="Edit Certification"><img src="/Content/images/icon/ico-sp_edituser2.gif"></a>
                        <a data-toggle="tooltip" data-placement="left" title="Delete Certification" onclick="deleteCertification('8');" style="cursor:pointer;"><img src="/Content/images/icon/ico-sp_deluser2.gif"></a>
                    </td>
                </tr>
                <tr class="main_table_row">
                    <td align="left" colspan="3">5555 </td>
                </tr>
            </tbody>
        </table>
    </div>*@