SupplierPortal/Models/Reports/ReportsModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SupplierPortal.Models.Reports
{
    public class ReportsModels
    {
        public string OrgID { get; set; }
        public string UserID { get; set; }
        public string RptID { get; set; }
    }
}

SupplierPortal/Controllers/ReportController.cs
using SupplierPortal.Models;
using SupplierPortal.Models.Reports;
using SupplierPortal.ReportSupport;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace SupplierPortal.Controllers
{

    public class ReportController : ControllerBase
    {

        // GET: Report
        public ActionResult Index()
        {
            return View();
        }

        #region SummaryReport(Main Page)

        //Key for DecryptString From BestSupply
        private static sbyte[] key2 = new sbyte[] { 94, 41, -98, -89, 81, -83, -108, 2, 127, 69, -39, -101, 47, 118, 59, 22, -83, 91, 26, -119, -62, 100, 79, -98 };
        
        [HttpPost]
        public ActionResult SummaryReportShow(DashboardModels model)
        {
            try
            {
                ClsReportChart oRptChart = new ClsReportChart();
                DataTable dtUserData = new DataTable();

                if (!string.IsNullOrEmpty(model.OrgID) && !string.IsNullOrEmpty(model.RptID))
                {
                    Session["suppShortName"] = model.OrgID;
                    Session["rptID"] = model.RptID;
                }
                else
                {
                    return RedirectToAction("Error", "Error", new { ErrorMessage = "Can not find report host configuration. Please contact your administrator." });
                }

                ClsSupportConnection connRpt = new ClsSupportConnection();
                if (connRpt.GetServerValueBySupplier(Session["suppShortName"].ToString()) == true)
                {
                    Session["LastUpdate"] = oRptChart.getRptLastUpdate(Convert.ToInt32(Session["rptID"])).Rows[0]["LastUpdated"];
                    //Session["LastUpdate"] = "";

                }
                else
                {
                    return RedirectToAction("Error", "Error", new { ErrorMessage = "Can not find report host configuration. Please contact your administrator." });
                    //return  RedirectToAction("~/Error/Timeout");
                }

                var dtBuyerGrp = new DataTable();
                dtBuyerGrp = oRptChart.getDtBuyerGrp(Session["suppShortName"].ToString());
                int buyerGrpRound = dtBuyerGrp.Rows.Count;

                var dtYear = new DataTable();
                dtYear = oRptChart.getDtYear();
                int yearRound = dtYear.Rows.Count;

                //************************
                //assign Value to Model
                //************************
                DashboardModels dashModel = new DashboardModels
                {

                    filter_BuyerGrps = Enumerable.Range(1, buyerGrpRound).Select(x => new BuyerGrpFilter
                    {
                        buyerGrpName = Convert.ToString(dtBuyerGrp.Rows[x - 1]["GroupName"])
                    }),
                    filter_Years = Enumerable.Range(1, yearRound).Select(x => new YearFilter
                    {
                        yearID = Convert.ToInt32(dtYear.Rows[x - 1]["Year"]),
                        yearName = Convert.ToString(dtYear.Rows[x - 1]["YearName"])
                    })
                };

                HttpCookie cookieYear = Request.Cookies.Get("_year");
                HttpCookie cookieBuyerGrp = Request.Cookies.Get("_buyer");

                HttpCookie C_orgID = Request.Cookies["_orgID"];
                HttpCookie C_rptID = Request.Cookies["_rptID"];

                string orgID = null;
                string rptID = null;

                if (model.selectedYear != 0)
                {
                    cookieYear.Value = model.selectedYear.ToString();
                    cookieBuyerGrp.Value = model.selectedBuyerGrp;
                    dashModel.selectedBuyerGrp = cookieBuyerGrp.Value;
                    dashModel.selectedYear = Convert.ToInt32(cookieYear.Value);
                }
                else
                {
                    dashModel.selectedBuyerGrp = cookieBuyerGrp.Value;
                    dashModel.selectedYear = Convert.ToInt32(cookieYear.Value);
                }

                if ((C_orgID != null) && (C_rptID != null) && (C_orgID.Value != "") && (C_rptID.Value != ""))
                {
                    dashModel.OrgID = C_orgID.Value.ToString();
                    dashModel.RptID = C_rptID.Value.ToString();
                }
                else
                {
                    C_orgID = new HttpCookie("_orgID");
                    C_rptID = new HttpCookie("_rptID");

                    //orgID = "metro";
                    orgID = model.OrgID;
                    rptID = model.RptID;

                    C_orgID.Value = orgID;
                    C_rptID.Value = rptID;
                }

                dashModel.RptLastUpdate = Session["LastUpdate"].ToString();

                DataRow[] result = dtBuyerGrp.Select("GroupName ='" + dashModel.selectedBuyerGrp + "'");

                var fiterCon = "";
                if (dashModel.selectedBuyerGrp == "All")
                    fiterCon = "All Buyer Group | " + dashModel.selectedYear;
                else
                    fiterCon = result[0]["GroupName"] + " | " + dashModel.selectedYear;
                dashModel.filterCondition = fiterCon;
                dashModel.RptLastUpdate = Session["LastUpdate"].ToString();

                Response.Cookies.Add(cookieYear);
                Response.Cookies.Add(cookieBuyerGrp);
                Response.Cookies.Add(C_orgID);
                Response.Cookies.Add(C_rptID);

                return View(dashModel);

            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", "Error", new { ErrorMessage = ex.Message });
            }
           
        }

         public ActionResult SummaryReportShow()
        {

            ClsReportChart oRptChart = new ClsReportChart();
            DataTable dtUserData = new DataTable();
            HttpCookie C_orgID = Request.Cookies.Get("_orgID");
            HttpCookie C_rptID = Request.Cookies.Get("_rptID");

            if ((C_orgID != null) && (C_rptID!= null) && (C_orgID.Value != "") && (C_rptID.Value != ""))
            {
                //Session["suppShortName"] = "metro";
                Session["suppShortName"] = C_orgID.Value.ToString();
                Session["rptID"] = C_rptID.Value.ToString();
            }
            else
            {
                //return PartialView("TimeOutError");
                RedirectToAction("Error", "Error", new { ErrorMessage = "Can not find report host configuration. Please contact your administrator." });
            }

            var dtBuyerGrp = new DataTable();
            dtBuyerGrp = oRptChart.getDtBuyerGrp(Session["suppShortName"].ToString());
            int buyerGrpRound = dtBuyerGrp.Rows.Count;

            var dtYear = new DataTable();
            dtYear = oRptChart.getDtYear();
            int yearRound = dtYear.Rows.Count;

            //************************
            //assign Value to Model
            //************************
            DashboardModels dashModel = new DashboardModels
            {
                filter_BuyerGrps = Enumerable.Range(1, buyerGrpRound).Select(x => new BuyerGrpFilter
                {
                    buyerGrpName = Convert.ToString(dtBuyerGrp.Rows[x - 1]["GroupName"])
                }),
                filter_Years = Enumerable.Range(1, yearRound).Select(x => new YearFilter
                {
                    yearID = Convert.ToInt32(dtYear.Rows[x - 1]["Year"]),
                    yearName = Convert.ToString(dtYear.Rows[x - 1]["YearName"])
                })
            };

            dashModel.OrgID = Session["suppShortName"].ToString();
            dashModel.RptID = Session["rptID"].ToString();

            HttpCookie cookieYear = Request.Cookies.Get("_year");
            HttpCookie cookieBuyerGrp = Request.Cookies.Get("_buyer");

            if ((cookieYear == null) && (cookieYear.Value == ""))
            {
                cookieYear.Value = dashModel.selectedYear.ToString();
                cookieBuyerGrp.Value = dashModel.selectedBuyerGrp;
            }
            else
            {
                dashModel.selectedBuyerGrp = cookieBuyerGrp.Value;
                dashModel.selectedYear = Convert.ToInt32(cookieYear.Value);
            }

            dashModel.RptLastUpdate = Session["LastUpdate"].ToString();

            DataRow[] result = dtBuyerGrp.Select("GroupName ='" + dashModel.selectedBuyerGrp + "'");

            var fiterCon = "";
            if (dashModel.selectedBuyerGrp == "All")
                fiterCon = "All Buyer Group | " + dashModel.selectedYear;
            else
                fiterCon = result[0]["GroupName"] + " | " + dashModel.selectedYear;
            dashModel.filterCondition = fiterCon;
            dashModel.RptLastUpdate = Session["LastUpdate"].ToString();

            Response.Cookies.Add(cookieYear);
            Response.Cookies.Add(cookieBuyerGrp);
            Response.Cookies.Add(C_orgID);
            Response.Cookies.Add(C_rptID);

            return View(dashModel);
        }
    
         public ActionResult PrintPage()
        {

            ClsReportChart oRptChart = new ClsReportChart();
            DataTable dtUserData = new DataTable();

           // HttpContext.Session["suppShortName"] = "metro";

            if ((Convert.ToString(HttpContext.Session["suppShortName"]) != "") && HttpContext.Session["suppShortName"] != null)
            {
                ClsSupportConnection connRpt = new ClsSupportConnection();
                connRpt.GetServerValueBySupplier(Session["suppShortName"].ToString());
                Session["LastUpdate"] = oRptChart.getRptLastUpdate(Convert.ToInt32(Session["rptID"])).Rows[0]["LastUpdated"];
                //Session["LastUpdate"] = "";
            }
            else

SupplierPortal/Views/Report/Index.cshtml
@{
    ViewBag.Title = "Supplier Dashboard";
}
<div class="row">
    @{ Html.RenderAction("SubMenuPortal", "MenuPortal"); }
</div>
<div class="row">
    <h3>Purchasing Reports</h3>
</div>
<div class="row">
    @* รูปภาพพื้นหลังที่โชว์หน้า index*@
    <div class="col-md-12 all_ep_content_wrapper">
    </div>
</div>

SupplierPortal/Views/Report/PrintPage.cshtml
@model SupplierPortal.Models.DashboardModels
<script src="@Url.Content("~/FusionCharts/FusionCharts.js")" type="text/javascript"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script>
<script>
    $(document).ready(function () {
        $("#filter_detail").html('@T("_MenuSub.SupplyTool.Report.ReportFilterDetail")&nbsp;:&nbsp;@(Model.filterCondition)');
                $('#user_name').html('@(Model.UserName)');
        //        $('#supplier_name').html('@(Model.SuppShortName)');
        setFooter();
        //$.unblockUI();
    });
</script>
@{
    ViewBag.Title = "Supplier Dashboard";
 Layout = "~/Views/Shared/_LayoutPrintReport.cshtml";
}
<div style="padding:0px 8px 0px 10px;">
    <div class="print_header">
        <div style="float:left;font-size:18px;">@T("_MenuSub.SupplyTool.Report.ReportDashBoardName")</div>
    </div>
</div>
@*<div class="ms_content">*@
<div style="padding:2px 8px 5px 8px; width: 825px;">
    <table>
        <tr>
            <td><div id="filter_detail" class="report_filter_detail" style="display:inline-block;"></div></td>
            <td></td>
            <td>
                <div style="float: right;">
                    <a href="javascript:printpage();">@T("_Report.Menu.Print")</a>
                    <a href="javascript:printpage();"><img src="../Content/images/printer.gif" /></a>
                </div>
            </td>
        </tr>
        <tr>
            <td>
                <table id="tbl_ChartNumPO" border="0" cellpadding="0" cellspacing="0" style="width: 540px; border:solid 1px #AAAAAA;">
                    <tr>
                        <td valign="top" align="center" style="padding:0;">
                            @*3D Pie Chart NumPO*@
                            <div id="ChartNumPO">
                                @Html.Action("_NumPO", "PrintReport", new { year = @Model.selectedYear, buyerGroupName = @Model.selectedBuyerGrp })
                            </div>
                        </td>
                    </tr>
                </table>
            </td>
            <td>
                <div style="padding-left:30px;"></div>
            </td>
            <td>

                <table id="tbl_ChartPOVolume" border="0" cellpadding="0" cellspacing="0" style="width: 540px; border:solid 1px #AAAAAA;">
                    <tr>
                        <td valign="top" align="center" style="padding:0;">
                            @*3D Pie Chart POVolume*@
                            <div id="ChartPOVolume">
                                @Html.Action("_POVolume", "PrintReport", new { year = @Model.selectedYear, buyerGroupName = @Model.selectedBuyerGrp })
                            </div>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr>
            <td>
                <div style="padding-left:30px;"></div>
            </td>
            <td>
                <div style="padding-left:30px;"></div>
            </td>
        </tr>
        <tr>
            <td>
                <div style="padding-top:22px;"></div>
                <table id="tbl_ChartPOStatus" border="0" cellpadding="0" cellspacing="0" style="width: 540px; border:solid 1px #AAAAAA;">
                    <tr>
                        <td valign="top" align="center" style="padding:0;">
                            @*3D Pie Chart POStatus*@
                            <div id="ChartPOStatus">
                                @Html.Action("_POStatus", "PrintReport", new { year = @Model.selectedYear, buyerGroupName = @Model.selectedBuyerGrp })
                            </div>
                        </td>
                    </tr>
                </table>
            </td>
            <td>
                <div style="padding-left:30px;"></div>
            </td>
        </tr>
    </table>
</div>
<div style="padding:0px 10px 0 20px;">
    <div class="print_by" align="right">
        Supplier: <span id="supplier_name"></span>
        @*&nbsp;พิมพ์โดย (Print By): <span id="user_name"></span>*@
        &nbsp;พิมพ์เมื่อวันที่ (Print Date):  <span id="print_date"></span>
    </div>
</div>
<div style="padding:12px 10px 10px 10px;">
    <div style="border-top:solid 1px #CCCCCC;"></div>
</div>

<script type="text/javascript">


    //Print
    function printpage() {
        //window.print();
        FusionCharts.printManager.enabled(true);
        FusionCharts.printManager.managedPrint();
    }

    function setFooter() {
        //var today = new Date();
        //var dd = today.getDate();
        //var mm = today.getMonth() + 1; //January is 0!
        //var hh = today.getHours();
        //var min = today.getMinutes();
        //var yyyy = today.getFullYear();
        //if (dd < 10) {
        //    dd = '0' + dd
        //}
        //if (mm < 10) {
        //    mm = '0' + mm
        //}
        //if (hh < 10) {
        //    hh = '0' + hh
        //}
        //if (min < 10) {
        //    min = '0' + min
        //}
        //today = mm + '/' + dd + '/' + yyyy + '&nbsp;' + hh + ':' + min;

        var d = new Date();
        var n = d.getUTCDate();
        var yyyy = d.getUTCFullYear();
        var MM = d.getUTCMonth() + 1;
        var hh = d.getUTCHours();
        var mm = d.getUTCMinutes();
        var utcst = d.toUTCString();
        if (n < 10) {
            n = '0' + n
        }
        if (MM < 10) {
            MM = '0' + MM
        }
        if (hh < 10) {
            hh = '0' + hh
        }
        if (mm < 10) {
            mm = '0' + mm
        }
        //document.getElementById("demo").innerHTML = n;
        document.getElementById("print_date").innerHTML = MM + '/' + n + '/' + yyyy + ' ' + hh + ':' + mm;

        $('#user_name').html('@(Model.UserName)');
        $('#supplier_name').html('@(Model.SuppShortName)');
        //$("#print_date").html(today);
    }

</script>

SupplierPortal/Views/Report/SummaryReport.cshtml
@{
    HttpCookie cookieYear = HttpContext.Current.Request.Cookies["_year"];
    HttpCookie cookieBuyerGrp = HttpContext.Current.Request.Cookies["_buyer"];

    DateTime dtYear = DateTime.Now;
    int SetYear = dtYear.Year;
    
    int Years = Convert.ToInt32(cookieYear.Value);
    if (Years == SetYear)
    {
        Years = -1;
    }

    var buyerGrp = cookieBuyerGrp.Value.ToString();
}

@model SupplierPortal.Models.DashboardModels
<script src="@Url.Content("~/FusionCharts/FusionCharts.js")" type="text/javascript"></script>

@*<script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript">
        google.load('visualization', '1', { 'packages': ['motionchart'] });
        google.setOnLoadCallback(drawChart);
        function drawChart() {
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'Fruit');
            data.addColumn('date', 'Date');
            data.addColumn('number', 'Sales');
            data.addColumn('number', 'Expenses');
            data.addColumn('string', 'Location');
            data.addRows([
          ['Apples', new Date(1988, 0, 1), 1000, 300, 'East'],
          ['Oranges', new Date(1988, 0, 1), 1150, 200, 'West'],
          ['Bananas', new Date(1988, 0, 1), 300, 250, 'West'],
          ['Apples', new Date(1989, 6, 1), 1200, 400, 'East'],
          ['Oranges', new Date(1989, 6, 1), 750, 150, 'West'],
          ['Bananas', new Date(1989, 6, 1), 788, 617, 'West']
        ]);
            var chart = new google.visualization.MotionChart(document.getElementById('chart_div'));
            chart.draw(data, { width: 600, height: 300 });
        }
    </script>*@

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script>
<script>
    $(document).ready(function () {
        setBreadcrumb();
        $("#filter_detail").html('@T("_MenuSub.SupplyTool.Report.ReportFilterDetail")&nbsp;:&nbsp;@(Model.filterCondition)');
        $("#LastUpdate").html('@(Model.RptLastUpdate)')
        //        $('#user_name').html('@(Model.UserName)');
        //        $('#supplier_name').html('@(Model.SuppShortName)');
        //$.unblockUI();
    });
</script>
@{
    ViewBag.Title = "Supplier Dashboard";
    //Layout = "~/Views/Shared/_LayoutReport.cshtml";
}
<div class="row">
    @{ Html.RenderAction("SubMenuPortal", "MenuPortal"); }
</div>
<div class="row">
    <div class="col-md-4 padding-none">
        @*<div class="report_content_menu">*@
        <div class="report_menu_header">
            @T("_MenuSub.SupplyTool.Report.ReportDashBoardName")
        </div>
        <div class="report_menu_header_edge"></div>
        @*</div>*@
    </div>
    <div class="col-md-4 padding-none">
    </div>
    <div class="col-md-4 padding-none">
    </div>
</div>

<div class="row">@*@using (Html.BeginForm(new { SID = @Model.SID}))*@
    @using (Html.BeginForm())
    {
        <table border="0" cellpadding="0" cellspacing="0" style="width: 100%;">
            <tr>
                <td style=" vertical-align:top;width:30%;" class="report_content_left_menu">
                    @*<div class="report_content_left_menu">*@
                    <table style="width: 100%;">
                        <tr>
                            <td class="report_topic" style="padding-left: 10px;">
                                <div>@T("_MenuSub.SupplyTool.Report.ReportFilter")</div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="report_topic_2" style="padding-left: 15px;">@T("_MenuSub.SupplyTool.Report.ReportYear")</div>
                                @{
                                            foreach (var year in Model.filter_Years)
                                            {
                                                 <div class="checkbox" style="padding-left:20px;  margin-top: 0px;  margin-bottom: 0px;">
                                                    @Html.RadioButtonFor(x => x.selectedYear, year.yearID)
                                                    @year.yearName
                                                 </div>
                                            }
                                }
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="report_topic_2" style="padding-left: 15px;">@T("_MenuSub.SupplyTool.Report.ReportBuyerGroup")</div>
                                @{
                                            foreach (var buyer in Model.filter_BuyerGrps)
                                        {
                                            <div class="checkbox" style="padding-left:20px;  margin-top: 0px;  margin-bottom: 0px;">
                                                @Html.RadioButtonFor(x => x.selectedBuyerGrp, buyer.buyerGrpName)
                                                @buyer.buyerGrpName
                                            </div>
                                        }
                                }
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div style="text-align:justify;padding-top:8px;">
                                    <input type="submit" value="@T("_MenuSub.SupplyTool.Report.ReportButton")" class="btn btn-primary" />
                                </div>
                            </td>
                        </tr>
                        @*</div>*@
                    </table>
                    @*</div>*@
                </td>

                @*<td class="report_content_right_menu">*@
                <td style=" vertical-align:top;padding-left:0px;width:70%;" >
                    <table style="width: 100%;">
                        <tr>
                            <td align="left" style="padding-left:10px;" class="report_topic"><div id="breadcrumb"></div></td>
                            <td class="report_topic"></td>
                            <td align="right" style="padding-right:10px;" class="report_topic">
                                @*<a href="javascript:Refresh();">Refresh</a>|*@@Html.ActionLink("Print Friendly", "PrintPage", new { year = @Model.selectedYear, buyerGroupName = @Model.selectedBuyerGrp })
                           @*@Ajax.ActionLink("Print Friendly2", "PrintPage", new { id = "" }, new AjaxOptions { HttpMethod = "POST" })*@
                             </td>
                        </tr>
                        <tr>
                            <td colspan="3" align="left"><div id="filter_detail" class="report_filter_detail" style="display:inline-block; padding-top:14px;padding-bottom:0;padding-left:10px;"></div> </td>
                        </tr>
                        <tr>
                            <td>
                                @*<div style="padding-top:22px;"></div>*@
                                <table id="tbl_ChartNumPO" border="0" cellpadding="0" cellspacing="0" style="width: 460px; border:solid 1px #AAAAAA;">
                                    <tr>
                                        <td valign="top" align="center" style="padding:0;">
                                            @*3D Pie Chart NumPO*@
                                            <div id="ChartNumPO">
                                                @*@Html.Action("_NumPO", "Report", new { year = -1, buyerGroupName = "All" })*@
                                                @Html.Action("_NumPO", "Report", new { year = Years, buyerGroupName = buyerGrp })
                                                @*@{ Html.Action("_NumPOGet", "Report", new { year = Years, buyerGroupName = buyerGrp }); }*@
                                            </div>
                                        </td>
                                    </tr>
                                </table>
                            </td>
                            <td>
                                <div style="padding-left:20px;"></div>
                            </td>
                            <td>
                                @*<div style="padding-top:22px;"></div>*@
                                <table id="tbl_ChartPOVolume" border="0" cellpadding="0" cellspacing="0" style="width: 460px; border:solid 1px #AAAAAA;">
                                    <tr>
                                        <td valign="top" align="center" style="padding:0;">
                                            @*3D Pie Chart POVolume*@
                                            <div id="ChartPOVolume">
                                                @*@Html.Action("_POVolume", "Report", new { year = -1, buyerGroupName = "All" })*@
                                                @Html.Action("_POVolume", "Report", new { year = Years, buyerGroupName = buyerGrp })
                                                @*@{ Html.Action("_POVolumeGet", "Report", new { year = Years, buyerGroupName = buyerGrp }); }*@
                                            </div>
                                        </td>
                                    </tr>
                                </table>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div style="padding-top:22px;"></div>
                                <table id="tbl_ChartPOStatus" border="0" cellpadding="0" cellspacing="0" style="width: 460px; border:solid 1px #AAAAAA;">
                                    <tr>
                                        <td valign="top" align="center" style="padding:0px;">
                                            @*3D Pie Chart POStatus*@
                                            <div id="ChartPOStatus">
                                                @*@Html.Action("_POStatus", "Report", new { year = -1, buyerGroupName = "All" })*@
                                                @Html.Action("_POStatus", "Report", new { year = Years, buyerGroupName = buyerGrp })
                                                @*@{ Html.Action("_POStatusGet", "Report", new { year = Years, buyerGroupName = buyerGrp }); }*@
                                            </div>
                                        </td>
                                    </tr>
                                </table>
                            </td>
                            <td>
                                <div style="padding-left:20px;"></div>
                            </td>
                            <td></td>
                        </tr>
                        <tr>
                            <td></td>
                            <td>
                                <div style="padding-left:20px;"></div>
                            </td>
                            <td valign="bottom" style="padding:6px 0 0 0;" align="right">
                                <div style="float:right;font-weight:bold;padding-top:1px;">@T("_MenuSub.SupplyTool.Report.ReportLastUpdate")&nbsp; <span id="LastUpdate"></span></div>
                                @*<div id="LastUpdate" style="float:right;font-weight:bold;padding:2px 2px 2px 4px;"></div>*@
                                <div class="data_end"></div>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
        </table>
    }
</div>
<script type="text/javascript">

    //    $.blockUI({
    //        message: $('#loadingMsg'),
    //        overlayCSS: { backgroundColor: '#FFFFFF' },
    //        css: {
    //            border: 'none',
    //            background: 'none',
    //            padding: '0px'
    //        }
    //    });

    function setBreadcrumb() {
        var bc_template = '@Html.ActionLink("Supplier Report", "GoMainHome", "Report")&nbsp;&gt;&nbsp;<span class="ms_breadcrumb_hl">Dashboard</span>';
        $("#breadcrumb").html(bc_template);
    }
    function Refresh() {
        window.location.href = window.location.href;
    }
    //function printpage() {
    //    var home_action = $('ReportForm').attr('action');
    //    var print_action = home_action.replace('/Report/', '/PrintReport/');
    //   alert(print_action);
    //   $('ReportForm').attr('target', '_blank');
    //   $('ReportForm').attr('action', print_action);
    //   $('ReportForm').submit();
    //   $('ReportForm').attr('target', '_self');
    //   $('ReportForm').attr('action', home_action);
    //}


    //    function closeit() {
    //        alert("close");

    //        $.ajax({
    //            type: "POST",
    //            cache: false,
    //            url: 'DeleteUserSession',
    //            success: function (data) {
    //                alert("end close");
    //            },
    //            error: function (data) {
    //                alert("error");
    //            }
    //        });

    //    }

</script>