SupplierPortal/Controllers/LandingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SupplierPortal.Data.Models.Repository.Topic;
using SupplierPortal.Data.Models.Repository.NewsDisplay;
using SupplierPortal.Framework.Localization;
using SupplierPortal.Framework.MethodHelper;
using System.IO;
using System.Web.Configuration;

namespace SupplierPortal.Controllers
{
    public class LandingController : BaseController
    {
        ITopicRepository _topicRepository;
        InewsDisplayRepository _newsDisplayRepository; 

        public LandingController()
        {
            _topicRepository = new TopicRepository();
            _newsDisplayRepository = new newsDisplayRepository();

        }

        public LandingController(
            TopicRepository topicRepository,
            newsDisplayRepository newsDisplayRepository
            )
        {
            _topicRepository = topicRepository;
            _newsDisplayRepository = newsDisplayRepository;

        }

        // GET: Landing
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult WhyVerification()
        {

            string languageId = "";

            HttpCookie cultureCookie = Request.Cookies["_culture"];

            if (cultureCookie != null)
            {
                languageId = cultureCookie.Value.ToString();

            }
            else
            {
                languageId = CultureHelper.GetImplementedCulture(languageId);// This is safe
            }

            var model = _topicRepository.GetResourceBody("Landing.TopMenu1", languageId);

            ViewBag.Body = model;

            return View();
        }

        public ActionResult ProcessofVerification()
        {

            string languageId = "";

            HttpCookie cultureCookie = Request.Cookies["_culture"];

            if (cultureCookie != null)
            {
                languageId = cultureCookie.Value.ToString();

            }
            else
            {
                languageId = CultureHelper.GetImplementedCulture(languageId);// This is safe
            }

            var model = _topicRepository.GetResourceBody("Landing.TopMenu2", languageId);

            ViewBag.Body = model;

            return View();
        }

        public ActionResult SuccessStories()
        {

            string languageId = "";

            HttpCookie cultureCookie = Request.Cookies["_culture"];

            if (cultureCookie != null)
            {
                languageId = cultureCookie.Value.ToString();

            }
            else
            {
                languageId = CultureHelper.GetImplementedCulture(languageId);// This is safe
            }

            var model = _topicRepository.GetResourceBody("Landing.TopMenu3", languageId);

            ViewBag.Body = model;

            return View();
        }

        public ActionResult PressSection()
        {

            string languageId = "";

            HttpCookie cultureCookie = Request.Cookies["_culture"];

            if (cultureCookie != null)
            {
                languageId = cultureCookie.Value.ToString();

            }
            else
            {
                languageId = CultureHelper.GetImplementedCulture(languageId);// This is safe
            }

            var model = _topicRepository.GetResourceBody("Landing.TopMenu4", languageId);

            ViewBag.Body = model;

            return View();
        }

        public ActionResult GetVerified()
        {

            string languageId = "";

            HttpCookie cultureCookie = Request.Cookies["_culture"];

            if (cultureCookie != null)
            {
                languageId = cultureCookie.Value.ToString();

            }
            else
            {
                languageId = CultureHelper.GetImplementedCulture(languageId);// This is safe
            }

            var model = _topicRepository.GetResourceBody("Landing.GetVerify", languageId);

            ViewBag.Body = model;

            return View();
        }

        public ActionResult FAQs()
        {

            string languageId = "";

            HttpCookie cultureCookie = Request.Cookies["_culture"];

            if (cultureCookie != null)
            {
                languageId = cultureCookie.Value.ToString();

            }
            else
            {
                languageId = CultureHelper.GetImplementedCulture(languageId);// This is safe
            }

            var model = _topicRepository.GetResourceBody("Landing.TopMenu5", languageId);

            ViewBag.Body = model;

            return View();
        }

        public ActionResult FirstPage(string sectionName = "")
        {

            string languageId = "";

            HttpCookie cultureCookie = Request.Cookies["_culture"];

            if (cultureCookie != null)
            {
                languageId = cultureCookie.Value.ToString();

            }
            else
            {
                languageId = CultureHelper.GetImplementedCulture(languageId);// This is safe
            }

            var model = _topicRepository.GetResourceBody(sectionName, languageId);

            ViewBag.Body = model;

            return View();
        }

        public FileResult Download(string type)
        {
            string languageID = "";
            languageID = CurrentTime.getLanguageID();
            string pathAttachment = WebConfigurationManager.AppSettings["pathAttachment"];
            string file = "";

            if (type == "AGOP")
            {
                switch (languageID)
                {
                    case "2":
                        file = pathAttachment + _topicRepository.GetDownloadLinkOPAgreement(Int32.Parse(languageID));
                        break;

                    case "1":
                    default:
                        file = pathAttachment + _topicRepository.GetDownloadLinkOPAgreement(Int32.Parse(languageID));
                        break;

                }
            }
            else if(type == "AG")
            {
                switch (languageID)
                {
                    case "2":
                        file = pathAttachment + _topicRepository.GetDownloadLinkAgreement(Int32.Parse(languageID));
                        break;

                    case "1":
                    default:
                        file = pathAttachment + _topicRepository.GetDownloadLinkAgreement(Int32.Parse(languageID));
                        break;

                }
            }

            byte[] fileBytes = System.IO.File.ReadAllBytes(@file);
            string virtualFilePath = @file;
            string fileName2 = Path.GetFileName(virtualFilePath);

            //var cd = new System.Net.Mime.ContentDisposition
            //{
            //    // for example foo.bak
            //    FileName = fileName2,

            //    // always prompt the user for downloading, set to true if you want 
            //    // the browser to try to show the file inline
            //    Inline = false,
            //};
            //Response.AppendHeader("Content-Disposition", cd.ToString());
            //return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet);

            return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, fileName2);
        }

        public ActionResult News(int newsId = 0)
        {
            int languageId = GetCurrentLanguageHelper.GetIntLanguageIDCurrent();

            var model = _newsDisplayRepository.GetNewsByNewsId(newsId, languageId);

            ViewBag.Body = model.NewsDetail;

            return View();
        }

        public FileResult DownloadNews(string filePath)
        {
            string pathAttachment = WebConfigurationManager.AppSettings["pathAttachment"];
            filePath = pathAttachment + filePath;

            if (!System.IO.File.Exists(@filePath))
            {
                filePath = @pathAttachment + @"\SWWDocuments\UserManualForDownload\EPInstruction.pdf";
            }


            byte[] fileBytes = System.IO.File.ReadAllBytes(@filePath);
            string virtualFilePath = @filePath;
            string fileName2 = Path.GetFileName(virtualFilePath);
            return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, fileName2);
        }

        public ActionResult Alive()
        {
            var computername = System.Environment.MachineName;

            ViewBag.Computername = computername;

            return View();
        }
    }
}

SupplierPortal/Controllers/UserCOCController.cs
using SupplierPortal.Data.Models.Repository.User;
using SupplierPortal.Data.Models.Repository.UserSession;
using SupplierPortal.MainFunction.Helper;
using SupplierPortal.ServiceClients;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;

namespace SupplierPortal.Controllers
{
    public class UserCOCController : BaseController
    {
        private readonly log4net.ILog logger = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
        IUserSessionRepository _userSessionRepository;
        IUserRepository _userRepository;
        TermAndConditionService _termAndConditionService;
        public UserCOCController()
        {
            _userSessionRepository = new UserSessionRepository();
            _userRepository = new UserRepository();
            _termAndConditionService = new TermAndConditionService();
        }

        // GET: UserCOC
        [HttpPost]
        public async Task<ActionResult> Accept()
        {
            bool isSuccess = false;
            HttpClient clientCoc = new HttpClient();

            string baseURL = WebConfigurationManager.AppSettings["baseURL"];

            string userGuid = Session["GUID"].ToString();
            var userSession = _userSessionRepository.GetUserSession(userGuid);
            var user = _userRepository.FindAllByUsername(userSession.Username);

            string urlClientCoc = string.Format("{0}api/coc/acknowledge/{1}", baseURL, userSession.Username);
            HttpContent content = new FormUrlEncodedContent(new List<KeyValuePair<string, string>>() {
                new KeyValuePair<string, string>("consentId", Session["CodeOfConductConsentId"].ToString()),
                new KeyValuePair<string, string>("dataSubject", userSession.Username),
                new KeyValuePair<string, string>("userAgent", Request.UserAgent),
                new KeyValuePair<string, string>("country", user.Locale),
                new KeyValuePair<string, string>("localIp", userSession.IPAddress),
                new KeyValuePair<string, string>("model", DetectDeviceHelper.GetDeviceType(Request.UserAgent)),
                new KeyValuePair<string, string>("osVersion", Request.Browser.Platform)
            });

            HttpResponseMessage responseCoc = clientCoc.PostAsync(urlClientCoc, content).Result;
            if (responseCoc.StatusCode == System.Net.HttpStatusCode.OK)
            {
                Session["IsAcceptCodeOfConduct"] = true;
                isSuccess = true;
            }

            return Json(isSuccess);
        }

        [HttpPost]
        public async Task<ActionResult> AcceptTermAndCondition()
        {
            bool isSuccess = false;
            HttpClient client = new HttpClient();

            string baseURL = WebConfigurationManager.AppSettings["baseURL"];

            string userGuid = Session["GUID"].ToString();
            var userSession = _userSessionRepository.GetUserSession(userGuid);
            var user = _userRepository.FindAllByUsername(userSession.Username);

            string urlClient = string.Format("{0}api/term/acknowledge/{1}", baseURL, userSession.Username);
            HttpContent content = new FormUrlEncodedContent(new List<KeyValuePair<string, string>>() {
                new KeyValuePair<string, string>("consentId", Session["TermAndCondtionConsentId"].ToString()),
                new KeyValuePair<string, string>("dataSubject", userSession.Username),
                new KeyValuePair<string, string>("userAgent", Request.UserAgent),
                new KeyValuePair<string, string>("country", user.Locale),
                new KeyValuePair<string, string>("localIp", userSession.IPAddress),
                new KeyValuePair<string, string>("model", DetectDeviceHelper.GetDeviceType(Request.UserAgent)),
                new KeyValuePair<string, string>("osVersion", Request.Browser.Platform)
            });

            HttpResponseMessage responseCoc = client.PostAsync(urlClient, content).Result;
            if (responseCoc.StatusCode == System.Net.HttpStatusCode.OK)
            {
                Session["IsAcceptTermCondition"] = true;
                isSuccess = true;
            }

            return Json(isSuccess);
        }
    }
}

SupplierPortal/Controllers/UserPDPAController.cs
using Microsoft.Owin.Security;
using SupplierPortal.Core.Caching;
using SupplierPortal.Data.CustomModels.Parameter;
using SupplierPortal.Data.Models.MappingTable;
using SupplierPortal.Data.Models.Repository.UserSession;
using SupplierPortal.ServiceClients;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;

namespace SupplierPortal.Controllers
{
    public class UserPDPAController : BaseController
    {

        private readonly log4net.ILog logger = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
        private UserPDPAService _userPDPAService;
        private readonly ICacheManager _cacheManager;

        IUserSessionRepository _userSessionRepository;
        public UserPDPAController()
        {
            _userPDPAService = new UserPDPAService();
            _userSessionRepository = new UserSessionRepository();
            _cacheManager = new MemoryCacheManager();
        }


        [AllowAnonymous]
        public async Task<ActionResult> InsertUserPDPA()
        {
            #region----------------------------Set Cookies Language By Link------------------------

            string guid = Session["GUID"].ToString();
            Users_PDPA users = new Users_PDPA()
            {
                Username = guid
            };
            bool result = await _userPDPAService.InsertUserPDPA(users);
            Session["isCheckConsent"] = true;
            #endregion
            return Json(true);
        }

        public IAuthenticationManager Authentication
        {
            get
            {
                return HttpContext.GetOwinContext().Authentication;
            }
        }

        [AllowAnonymous]
        public async Task<ActionResult> GotoIndex()
        {
            try
            {
                string userGuid = "";

                if (Session["GUID"] != null)
                {
                    userGuid = Session["GUID"].ToString();

                    var userSession = _userSessionRepository.GetUserSession(userGuid);

                    if (userSession != null)
                    {
                        userSession.isTimeout = 1;
                        userSession.LogoutTime = DateTime.UtcNow;
                        _userSessionRepository.Update(userSession);
                    }
                }
            }
            catch (Exception ex)
            {
                logger.Error("Logout Controller : " + ex);
            }
            finally
            {
                Authentication.SignOut();
                _cacheManager.Clear();
                Session["username"] = null;
                Session["GUID"] = null;
                Session["Org"] = null;
                Session["user"] = null;
            }

            return Json(true);
        }
    }
}

SupplierPortal/Views/AccountPortal/Landingpage.cshtml
@{
    ViewBag.Title = "Landingpage";
    Layout = "~/Views/Shared/_LayoutLoginPortal.cshtml";
}

<div class="row">
    <div class="col-md-4 col-md-offset-5">
        @Html.ActionLink(T("Members").ToString(), "Login", "AccountPortal", null, new { @class = "btn btn-success btn-sm" })
        @Html.ActionLink(T("Non-Members").ToString(), "SupplierRegister", "RegisterPortal", null, new { @class = "btn btn-success btn-sm" })
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SupplierPortal/Views/AccountPortal/Login.cshtml
@model SupplierPortal.Data.Models.SupportModel.AccountPortal.LoginPortalModel
@using System.Web.Configuration;
@{
    ViewBag.Title = "Login - Supplier Web Work";
    Layout = "~/Views/Shared/_LayoutLoginPortal.cshtml";
    string LanguageId = (string)ViewBag.LanguageId;
    int lockedTime = ViewBag.lockTimeSeconds ?? 0;

    bool redirectToSC = !string.IsNullOrEmpty(WebConfigurationManager.AppSettings["join_now_url"]);
}
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
<div class="row">
    <div class="col-sm-3 col-sm-offset-7 ep_box_wrapper">
        <div class="ep_box_body">
            @using (Html.BeginForm("Login", "AccountPortal", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form", id = "form-login" }))
            {

                <div class="ep_box_content">
                    <div class="ep_box_topic">@T("_Login.LblMyAccount")</div>
                    <div class="ep_login_wrapper">
                        @Html.TextBoxFor(m => m.Username, new { @class = "username_txt_box", id = "username", maxlength = "50", placeholder = T("_Login.TxtUsername") })
                        @Html.ValidationMessageFor(m => m.Username, "", new { @class = "text-danger-bold" })
                    </div>
                    <div class="ep_pwd_wrapper">
                        @Html.PasswordFor(m => m.Password, new { @class = "pwd_txt_box", id = "password", maxlength = "50", placeholder = T("_Login.TxtPassword") })
                        @Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger-bold" })
                    </div>
                    @Html.Raw(HttpUtility.HtmlDecode(Html.ValidationMessage("Error", new { @class = "text-danger-bold" }).ToHtmlString()))
                    @*@Html.ValidationMessage("Error", new { @class = "text-danger-bold" })*@
                    @*<div id="login_error_box" class="login_error_box" style="display:block;">
                            <div id="login_error">
                                @{
                                    string validationMessage = string.Format(T("_Login.ValidateMsg.UsernameLock").ToString(), "5", "<span id='countDownTime'></span>");
                                    @Html.Raw(validationMessage)
                                }
                            </div>
                        </div>*@
                    <div class="ep_submit_wrapper">
                        <input type="submit" value="@T("_Login.BtnLogin")" class="btn_login" onclick="submitLogin();" />
                        @{
                            var spans = T("_login.Btnlink_Regis").ToString().Split('_').ToList();
                            if (spans.Count == 2)
                            {
                                if (redirectToSC)
                                {
                                    spans[1] = string.Format("<a href='{0}'>{1}</a>"
                                    , Url.Action("RedirectRegisterSC", "Redirect")
                                    , spans[1]);
                                }
                                else
                                {
                                    spans[1] = string.Format("<a href='{0}'>{1}</a>"
                                        , Url.Action("SupplierRegister", "Register")
                                        , spans[1]);
                                }
                            }
                        }
                        <span style='padding-left: 15px;color:#808080'>
                            @Html.Raw(string.Join("", spans))
                        </span>
                    </div>
                    <div class="ep_forgot_pwd">
                        @Html.ActionLink(T("_Login.LblForgotPassword").ToString(), "ForgotPasswordConfirmation", "AccountPortal")
                    </div>
                </div>
            }
        </div>
    </div>
</div>

<div class="modal modal-pdpa fade" id="termModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-agree">
        <div class="modal-content">
            <div class="modal-body p-0 overflow-hidden" style="overflow-y: auto;">
                <div class="nav-custom">
                    <div class="nav-tabs">
                        <a href=".tab-1" id="term_tab_1" data-toggle="tab" title="@T("_Agreement.TermAndCondition.TermService")" class="active" onclick="clickTabTermPrivacy('term_tab_1')">@T("_Agreement.TermAndCondition.TermService")</a>
                        <a href=".tab-2" id="term_tab_2" data-toggle="tab" title="@T("_Agreement.TermAndCondition.PrivacyPolicy")" onclick="clickTabTermPrivacy('term_tab_2')">@T("_Agreement.TermAndCondition.PrivacyPolicy")</a>
                        <div class="lang">
                            <div class="btn-group">
                                <img src="~/Content/images/icon/sphere.png" class="sphere" />
                                <a class="btn dropdown-toggle" id="lang_value" data-toggle="dropdown">
                                    EN
                                </a>
                                <ul class="dropdown-menu dropdown-pdpa" role="menu" aria-labelledby="dLabel">
                                    <li>
                                        <a href="#" id="term_lang_en" data-title="EN" class="dropdown-item active" onclick="clickSwitchTermLanguage('term_lang_en')">English</a>
                                    </li>
                                    <li>
                                        <a href="#" id="term_lang_th" data-title="TH" class="dropdown-item" onclick="clickSwitchTermLanguage('term_lang_th')">ภาษาไทย</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    @*EN*@
                    <div id="term_content" class="tab-content">
                        <div class="tab-1 tab-pane active">
                            <div id="term_content_en">
                                @Html.Raw(WebUtility.HtmlDecode(@ViewBag.TermAndConditionEN))
                            </div>
                            <div id="term_content_th">
                                @Html.Raw(WebUtility.HtmlDecode(@ViewBag.TermAndConditionTH))
                            </div>
                        </div>
                        <div class="tab-2 tab-pane">
                            <div id="notice_content_en">
                                @Html.Raw(WebUtility.HtmlDecode(@ViewBag.PrivacyNoticeEN))
                            </div>
                            <div id="notice_content_th">
                                @Html.Raw(WebUtility.HtmlDecode(@ViewBag.PrivacyNoticeTH))
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <div class="float-custom">
                    <button type="button" id="btnTermDecline" data-dismiss="modal" class="btn btn-noborder">
                        @T("_Agreement.TermAndCondition.DeclineLogOut")
                    </button>
                    <button type="button" id="btnTermApprove" class="btn btn-primary">
                        @T("_Agreement.TermCondition.BtnOk")
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">

        function clickTabTermPrivacy(tabId) {
            var tabChange = 'term_tab_1';
            if (tabId == 'term_tab_1') {
                tabChange = 'term_tab_2';
            }

            $("#" + tabChange).removeClass("active");
            $("#" + tabId).addClass("active");
        }

        function clickSwitchTermLanguage(lang) {
            var langChange = 'term_lang_th';
            var langId = 1;
            if (lang == 'term_lang_th') {
                langChange = 'term_lang_en';
                langId = 2;
            }

            $("#" + langChange).removeClass("active");
            $("#" + lang).addClass("active");

            setDropdownTermCondition(langId);
        }

        function setDropdownTermCondition(langId) {
             if (langId == 1) {
                $('#term_content_en').show();
                $('#term_content_th').hide();

                $('#notice_content_en').show();
                $('#notice_content_th').hide();

                $('#lang_value').text('EN')
            }

            if (langId == 2) {
                $('#term_content_en').hide();
                $('#term_content_th').show();

                $('#notice_content_en').hide();
                $('#notice_content_th').show();

                $('#lang_value').text('TH')
            }
        }

        $('.dropdown-toggle').dropdown()

        $(window).load(function () {
            clickTabTermPrivacy('term_tab_2')
            setDropdownTermCondition(@LanguageId);
            if ("@ViewBag.IsShowModalTerm" == "True") {
                $('#termModal').modal({ 'show': true, backdrop: 'static', keyboard: false });
            }
        });

        $("#termModal .close").click(function () {
            $('#termModal').modal('toggle');
            disablePage();
            signOut();
        });

        $("#btnTermApprove").click(function () {
            var origin = $(location).attr('origin');
            disablePage();
            $.ajax({
                url: '@Url.Action("AcceptTermAndCondition", "UserCOC")',
                type: 'POST',
                data: '',
                async: false,
                contentType: 'application/json',
                success: function (data) {
                    $('#termModal').modal('toggle');
                    window.location = origin + "/Home/Index"
                },
                fail: function (event, data) {
                    window.location = origin + "/AccountPortal/Login"
                }
            });
        });

        $("#btnTermDecline").click(function () {
            disablePage();
            signOut();
        });


        function signOut() {
            var origin = $(location).attr('origin');
            disablePage();
            $.ajax({
                url: '@Url.Action("GotoIndex", "UserPDPA")',
                type: 'POST',
                data: '',
                async: false,
                contentType: 'application/json',
                success: function (data) {
                    window.location = origin + "/AccountPortal/Login"
                },
                fail: function (event, data) {
                    window.location = origin + "/AccountPortal/Login"
                }
            });
        }

</script>


@{ Html.RenderAction("NewsFeedsPartial", "AccountPortal"); }

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
<script type="text/javascript">

    var isLocked = document.getElementById('countDownTime');

    var now = new Date();
    now.setSeconds(now.getSeconds() + @lockedTime);

    var countDownDate = now.setMinutes(now.getMinutes() + (30 / 60));

    //var countDownDate = new Date("Jan 5, 2018 15:37:25").getTime();
    var x = setInterval(function () {

        // Get todays date and time
        var now = new Date().getTime();

        // Find the distance between now an the count down date
        var distance = countDownDate - now;

        // Time calculations for days, hours, minutes and seconds
        var days = Math.floor(distance / (1000 * 60 * 60 * 24));
        var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
        var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
        var seconds = Math.floor((distance % (1000 * 60)) / 1000);

        var strCountDown = "";
        if (days > 0)
        {
            strCountDown += days + "d ";
        }
        if (hours > 0) {
            strCountDown += hours + "h ";
        }
        if (minutes > 0) {
            strCountDown += minutes + "m ";
        }
        // Output the result in an element with id="demo"
        document.getElementById("countDownTime").innerHTML = strCountDown + seconds + "s ";

        // If the count down is over, write some text
        if (distance < 0) {
            clearInterval(x);
            document.getElementById("countDownTime").innerHTML = "0 s";
        }
    }, 1000);

    if (isLocked === null)
    {
        clearInterval(x);
    }

    function submitLogin() {
        //var chkUsername = $("#username").hasClass("valid");
        //var chkPassword = $("#password").hasClass("valid");
        //if (chkUsername && chkPassword) {
        //    disablePage();
        //}
        var $form = $("#form-login");
        if ($form.valid()) {
            disablePage();
            //$form.submit();
        }
    }
</script>